image: node:14.17.0

stages:
  - build
  - deploy

build:
  stage: 'build'
  script:
    - npm install -y npm@6.11.0
    - nodejs -v
    - npm -v
    - ls -la -F
    - npm ci
    - npx ng build --prod
  cache:
    paths:
      - node_modules/
  artifacts:
    when: on_success
    name: '$CI_JOB_NAME-$CI_COMMIT_REF_NAME'
    paths:
      - dist/angular-gitlab-ci-cd-example/
  only:
    - master

deploy:
  stage: deploy
  image: python:latest
  script:
    - apt-get update -qq && apt-get install -y -qq python3-pip
    - pip3 install --upgrade awscli
    - pip3 install --upgrade awsebcli
    - echo "DEPLOYMENT_ENV=production" >> .env
    - echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env
    - echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
    - echo "AWS_REGION=us-east-1" >> .env
    - eb init -r us-east-1 -p Node.js 14 AngularEB
    - eb deploy
  only:
    - master
