image: node:14

stages:
  - build
  - package
  - deploy

build:
  stage: build
  before_script:
  - npm ci
  script:
    - npm run build

package:
  stage: package
  script:
    - apt-get update && apt-get install -y zip
    - zip -r app.zip dist/*

deploy:
  stage: deploy
  image: python:3.8
  script:
    - apt-get update && apt-get install -y zip
    - pip install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 cp ./dist s3://bucket-ecs1/ --recursive
    - aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
